# 应用服务 WEB 访问端口
#server.port=8080

#  配置数据库
spring:
  application:
    name: TadowsV1Application
  datasource:
    name: tadows_weather_system
    url: jdbc:mysql://localhost:3306/tadows_weather_system?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: GemendeMySQLsju1!(?)
    driver-class-name: com.mysql.cj.jdbc.Driver

#  配置MyBatisPlus
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto


